spring:
  application:
    name: test-product-enquiry-service

server:
  port: ${port:8700}
#
#test-product-stock-service:
#  ribbon:
#    listOfServers: http://localhost:8800, http://localhost:8801
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}