spring:
  application:
    name: test-product-stock-sevice

server:
  port: ${port:8800}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#eureka:
#  client:
#    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}