spring:
  application:
    name: test-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pratd/environment-variable-repo.git
          default-label: main
server:
  port: ${port:8888}
